// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/author/[id]" | "/design/[slug]" | "/designs/[slug]" | "/explore" | "/forum" | "/resources/[slug]" | "/submit"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/categories" | "/api/copies" | "/api/designs" | "/api/designs/[slug]" | "/api/designs/[slug]/bookmark" | "/api/designs/[slug]/comments" | "/api/designs/[slug]/likes" | "/api/designs/[slug]/ratings" | "/api/designs/[slug]/remix" | "/api/designs/featured" | "/api/locale" | "/api/resources" | "/api/resources/[slug]" | "/api/resources/[slug]/bookmark" | "/api/resources/[slug]/comments" | "/api/resources/[slug]/likes" | "/api/resources/[slug]/ratings" | "/api/resources/[slug]/remix" | "/api/resources/dictionary" | "/api/resources/featured" | "/api/search-facets" | "/api/uploads"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/categories": {}
  "/api/copies": {}
  "/api/designs": {}
  "/api/designs/[slug]": { "slug": string; }
  "/api/designs/[slug]/bookmark": { "slug": string; }
  "/api/designs/[slug]/comments": { "slug": string; }
  "/api/designs/[slug]/likes": { "slug": string; }
  "/api/designs/[slug]/ratings": { "slug": string; }
  "/api/designs/[slug]/remix": { "slug": string; }
  "/api/designs/featured": {}
  "/api/locale": {}
  "/api/resources": {}
  "/api/resources/[slug]": { "slug": string; }
  "/api/resources/[slug]/bookmark": { "slug": string; }
  "/api/resources/[slug]/comments": { "slug": string; }
  "/api/resources/[slug]/likes": { "slug": string; }
  "/api/resources/[slug]/ratings": { "slug": string; }
  "/api/resources/[slug]/remix": { "slug": string; }
  "/api/resources/dictionary": {}
  "/api/resources/featured": {}
  "/api/search-facets": {}
  "/api/uploads": {}
  "/author/[id]": { "id": string; }
  "/design/[slug]": { "slug": string; }
  "/designs/[slug]": { "slug": string; }
  "/explore": {}
  "/forum": {}
  "/resources/[slug]": { "slug": string; }
  "/submit": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
