// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/author/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/author/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/author/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/design/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/designs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/designs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/designs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../src/app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum">> = Specific
  const handler = {} as typeof import("../../src/app/forum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/resources/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/resources/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submit">> = Specific
  const handler = {} as typeof import("../../src/app/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/copies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copies">> = Specific
  const handler = {} as typeof import("../../src/app/api/copies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/[slug]/bookmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/[slug]/bookmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/[slug]/bookmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/[slug]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/[slug]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/[slug]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/[slug]/likes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/[slug]/likes">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/[slug]/likes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/[slug]/ratings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/[slug]/ratings">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/[slug]/ratings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/[slug]/remix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/[slug]/remix">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/[slug]/remix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/featured/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs/featured">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/featured/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/designs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs">> = Specific
  const handler = {} as typeof import("../../src/app/api/designs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locale">> = Specific
  const handler = {} as typeof import("../../src/app/api/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/[slug]/bookmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/[slug]/bookmark">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/[slug]/bookmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/[slug]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/[slug]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/[slug]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/[slug]/likes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/[slug]/likes">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/[slug]/likes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/[slug]/ratings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/[slug]/ratings">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/[slug]/ratings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/[slug]/remix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/[slug]/remix">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/[slug]/remix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/dictionary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/dictionary">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/dictionary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/featured/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/featured">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/featured/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search-facets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search-facets">> = Specific
  const handler = {} as typeof import("../../src/app/api/search-facets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
